version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: product_management_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: product_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  redis:
    image: redis:7
    container_name: product_management_redis
    ports:
      - "6379:6379"
    networks:
      - backend_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: product_management_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672" # Management console
    networks:
      - backend_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product_management_api
    depends_on:
      - postgres
      - redis
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: product_db
      DB_HOST: postgres
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data:
